server:
  port: 5000
spring:
  datasource:
    #url: jdbc:mysql://192.168.99.100:32768/ebdb
    #username: demo_user
    #password: demo-password
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:h2:mem:;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    initialize: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
